---
name: "1. (tzarc) Create Build Container"

on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 */6 * *' # every 6 days to keep cache
permissions:
  contents: read
  packages: write

env:
  TC_WORKDIR: '/t'
  EXECUTE_UNDER_DOCKER: true
  CROSSTOOL_REPO_REF: 63fdc9cb3735aa8da4381f0a59169e55a8590d11

jobs:
  base_container:
    # only actually execute on @tzarc's repo so as to not lock up QMK org's resources
    if: github.repository == 'tzarc/qmk_toolchains'

    name: "Build base container"
    runs-on: ubuntu-latest

    steps:
      - name: Move docker data root to /mnt for more space
        run: |
          DOCKER_DATA_ROOT='/mnt/var/lib/docker'
          DOCKER_DAEMON_JSON='/etc/docker/daemon.json'
          sudo mkdir -p "${DOCKER_DATA_ROOT}"
          echo "{\"data-root\": \"${DOCKER_DATA_ROOT}\"}" | sudo tee "${DOCKER_DAEMON_JSON}"
          sudo systemctl restart docker
          sudo df -h

      - name: "Clone toolchains repo"
        uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          build-args: |
            CROSSTOOL_REPO_REF=${{ env.CROSSTOOL_REPO_REF }}
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/tzarc/qmk_toolchains:base

  tarballs:
    # only actually execute on @tzarc's repo so as to not lock up QMK org's resources
    if: always() && !cancelled() && github.repository == 'tzarc/qmk_toolchains'

    name: "Download required tarballs"
    runs-on: ubuntu-latest
    needs: [base_container]

    steps:
      - name: "Setup docker workspace"
        run: |
          sudo mkdir $TC_WORKDIR
          sudo mount --bind $GITHUB_WORKSPACE $TC_WORKDIR

      - name: "Clone toolchains repo"
        uses: actions/checkout@v4

      - name: Cache check
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            *.sh
            Dockerfile*
            common.bashinc
            tarballs.tar
          key: cache-tarballs-${{ hashFiles('*.sh', 'Dockerfile*', 'common.bashinc') }}

      - name: "Gather source tarballs"
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          # Clear out the tools prefix so we can run everything, even without a bootstrap compiler present
          for f in $(ls -1 *.sh | grep -E '(native|canadian)'); do
            ./$f --tools-prefix= source --container-image=ghcr.io/tzarc/qmk_toolchains:base
          done
          tar cvf tarballs.tar tarballs

      - name: "Upload source tarballs"
        uses: actions/upload-artifact@v4
        with:
          name: tarballs.tar
          path: tarballs.tar

  # Build a copy of linux/X64 toolchain to bootstrap the rest so that the resulting compilers are compatible with the old glibc.
  bootstrap-linuxX64-toolchain:
    # only actually execute on @tzarc's repo so as to not lock up QMK org's resources
    if: always() && !cancelled() && github.repository == 'tzarc/qmk_toolchains'

    name: "Build bootstrap linuxX64 toolchain"
    needs: [tarballs]
    uses: ./.github/workflows/compile_one_toolchain.yaml
    with:
      crosstool_host_os: linuxX64
      build_host: linuxX64
      target_host: linuxX64
      build_script: x64linux-native-bootstrap.sh
      fetch_bootstrap: false
      toolchain_suffix: "_qmk_bootstrap"

  # Build base toolchains
  base-toolchains:
    # only actually execute on @tzarc's repo so as to not lock up QMK org's resources
    if: always() && !cancelled() && github.repository == 'tzarc/qmk_toolchains'

    name: "Build base toolchains"
    needs: [bootstrap-linuxX64-toolchain]
    strategy:
      fail-fast: false
      matrix:
        target_host: [linuxX64, linuxARM64, windowsX64]
        include:
          - target_host: linuxX64
            build_script: x64linux-native.sh
          - target_host: linuxARM64
            build_script: aarch64linux-native.sh
          - target_host: windowsX64
            build_script: win64-native.sh
    uses: ./.github/workflows/compile_one_toolchain.yaml
    with:
      crosstool_host_os: linuxX64
      build_host: linuxX64
      target_host: ${{ matrix.target_host }}
      build_script: ${{ matrix.build_script }}
